creation_rules:

  - path_regex: sops-secret\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: &ageKeys |-
      age1s7tlxg30wl7spadyyztffce4y9k3rl05wuc5vavpcn933s4sk40q0dm63h,
      age1gkm9q535q4qc2mhlrkgzl45xwmpf8jg4fstya7jnatstg7grrdns4rtp2x
  # keys:
  # - personal
  # - cluster key
  - path_regex: secrets.yaml
    age: age1s7tlxg30wl7spadyyztffce4y9k3rl05wuc5vavpcn933s4sk40q0dm63h
  - age: *ageKeys
