creation_rules:

  - path_regex: sops-secret\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: &ageKeys |-
      age1cydkdqcsl9dzuze2uh65crllur9lkmfxcmew7w3us8cq87kcz39qc0yyhj,
      age1sajn4hle45ywde4g2zm6qaktj6ucsuv8cpd8kuzfnqny538r5u8qyq32sa
  # keys:
  # - personal
  # - cluster key
  - age: *ageKeys
