apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: sops-secrets-operator
  namespace: kube-system
spec:
  interval: 30m
  url: https://isindir.github.io/sops-secrets-operator/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sops-secrets-operator
  namespace: kube-system
spec:
  releaseName: sops-secrets-operator
  chart:
    spec:
      chart: sops-secrets-operator
      sourceRef:
        kind: HelmRepository
        name: sops-secrets-operator
        namespace: kube-system
      version: 0.9.1
  interval: 1h0m0s
  values:
    image:
      repository: isindir/sops-secrets-operator
      tag: 0.3.2
    secretsAsFiles:
      - name: age
        mountPath: /etc/age
        secretName: sops-age
    extraEnv:
      - name: SOPS_AGE_KEY_FILE
        value: /etc/age/age.agekey 
