apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-issuers
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./cert-manager-issuers
  prune: true
  validation: client
