apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: vertical-pod-autoscaler
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-issuers
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./vertical-pod-autoscaler
  prune: true
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: vpa-admission-controller
      namespace: kube-system
    - apiVersion: apps/v1
      kind: Deployment
      name: vpa-recommender
      namespace: kube-system
    - apiVersion: apps/v1
      kind: Deployment
      name: vpa-updater
      namespace: kube-system
