apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coder
  namespace: coder
spec:
  interval: 5m
  chart:
    spec:
      chart: coder
      version: 1.21.1
      sourceRef:
        kind: HelmRepository
        name: coder
        namespace: flux-system
  values:
    coderd:
      serviceNext: true
      devurlsHost: '*.devurls.samcday.com'
      serviceSpec:
        type: ClusterIP
        loadBalancerIP: null
        externalTrafficPolicy: null
        loadBalancerSourceRanges: null
    ingress:
      enable: true
      host: coder.samcday.com
      useDefault: false
      annotations: {} # external-dns
    postgres:
      default:
        storageClassName: hcloud-volumes
