apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/download/v1.12.0/ccm-networks.yaml
patches:
  - target:
      kind: Deployment
      name: hcloud-cloud-controller-manager
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/env/2/valueFrom
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: network
