name: Build image

on:
  push:
    branches: [main]
    paths: [image/**, .github/workflows/image.yaml]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: 'true'
      - run: image/build.sh
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
